### ISSUE TITLE
Not Compatible with mobs from other mods

### ISSUE THREAD

**Issue by Bolism233** [Skullman-G/MC-Dark-Souls#13]
Mobs from other mods deals damage that cannot be blocked by shield.
In other words, the shield does not block,
For example, mobs from Twilight forest. 
Anyway to fix that?

**Comment by Skullman-G** [comment]
Hmmm... Let's see.

**Comment by Bolism233** [comment]
Even spider's attack is ignoring the shield. I only installed this mod and twilight forest.

**Comment by Skullman-G** [comment]
Fixed it.
