### ISSUE TITLE
Crash on start 1.16.5

### ISSUE THREAD

**Issue by Tempish** [Skullman-G/MC-Dark-Souls#19]
Forge 36.2.39
Here's the crash log:
[crash-2022-08-31_14.12.19-fml.txt](https://github.com/Skullman-G/MC-Dark-Souls/files/9464881/crash-2022-08-31_14.12.19-fml.txt)
Mod list:
![image](https://user-images.githubusercontent.com/92348966/187778579-29f67297-68f3-46c2-8989-216c7527d912.png)

**Comment by Skullman-G** [comment]
I fixed the crash already but haven't published a patch yet. I will close issue once I did.
