### ISSUE TITLE
Incompatibility with Mekanism radiation

### ISSUE THREAD

**Issue by border999** [Skullman-G/MC-Dark-Souls#30]
https://gist.github.com/border999/4a802eaf443ddc52d63d84108fe4da27

**Comment by border999** [comment]
I honestly recommend just trying to run dark souls with Mekanism and seeing what goes awry. It's too much to put here.

**Comment by Skullman-G** [comment]
Yeah, I see the problem. At first I thought it was the fault of mekanism but it is truly the fault of my mod. But it should be an easy fix. I will collect some other bug fixes or add some minor features and tweaks to round it up to a new minor version.
