### ISSUE TITLE
crash on start up 

### ISSUE THREAD

**Issue by thiccmeme** [Skullman-G/MC-Dark-Souls#6]
[crash-2021-12-25_16.37.20-server.txt](https://github.com/Skullman-G/MC-Dark-Souls/files/7776372/crash-2021-12-25_16.37.20-server.txt)

attached is the crash report running forge 1.16.5 36.2.20

**Comment by thiccmeme** [comment]
[crash-2021-12-25_16.41.12-server.txt](https://github.com/Skullman-G/MC-Dark-Souls/files/7776374/crash-2021-12-25_16.41.12-server.txt)
just for good measure, the same issue with no other mods installed, crashing on client trying to create a world.

**Comment by Skullman-G** [comment]
It is an issue my mod has with the forge mod loader above 1.16.5 36.2.0. I did not find a solution to play on higher versions yet but it still works on 1.16.5 36.2.0 and below.
